### ISSUE TITLE
Revert podspec AFNetworking dependency

### ISSUE THREAD

**Issue by metova-developer** [jeyben/IOSLinkedInAPI#19]
It looks like you updated the podspec for 1.0.0 a month ago so that the AFNetworking dependency is version 1.3.3. It used to be 1.2.1, which is what I've been using in my app. Since the pod version wasn't updated with this change, pod install fails for me unless I change my AFNetworking version to 1.3.3. However, when I do that, I run into other problems with your linkedin pod.

I think the pod version should have been updated to 1.0.1 when the AFNetworking dependency version changed. Oddly enough, your repo shows 1.2.2 as the dependency for version 1.0.0, but Cocoapods shows 1.3.3.

Here's the Cocoapods podspec for version 1.0.0: https://github.com/CocoaPods/Specs/blob/master/IOSLinkedInAPI/1.0.0/IOSLinkedInAPI.podspec

And here's your current one: https://github.com/jeyben/IOSLinkedInAPI/blob/1.0.0/IOSLinkedInAPI.podspec

With that being said, thanks for making a great LinkedIn library!

**Comment by simonhamadene** [comment]
Hi Jacob,

I am trying to use IOSLinkedInAPI in my project. I need some help please.
here is what I did:

1. I added "Podfile" and "Podfile.lock" in the folder where my project file is.
2. From Terminal shell, from the folder where "Podfile" is, I did : pod install then Podfile folder has been created.
3. in my ViewController.mI added this:
#import "AFHTTPRequestOperation.h"
#import "LIALinkedInHttpClient.h"
#import "LIALinkedInApplication.h"

the compiler does not complain but the linker does.

then I was wondering shall I add the .m of these files into "Build Phases" --> "Compile Sources" ?
this means that the whole library has to be re-compiled and re-linked?  
is this right? I was hoping not to re-do the recompiling of the library?

**Comment by simonhamadene** [comment]
Hi Jacob,

I could fix my linking problem (see above). I just added the flag $(inherited) "recursive" in the HEADER_SEARCH_FLAGS and OTHER_LDFLAGS .

Thanks,
