### ISSUE TITLE
not showing Login Window for LinkedIn API in iOS

### ISSUE THREAD

**Issue by AnilkumarRabhasa** [jeyben/IOSLinkedInAPI#35]
Mr. Jeyben, thanks for sharing great api for integrating the LinkedIn Api to iOS apps. This saves my time for integarting to my app. Yesterday i downloaded this api and i got user info from LinkedIn. Today i opend my app, the login window not showing after clicking the button. Its very strange to me really, i checked my code perfectly, i dint changed anything. Could you pls give solution for this, Thanks in advanced.

**Comment by BruhhGarcia** [comment]
Any solution? I'm having the same problem..

**Comment by datomnurdin** [comment]
Is there any solutions for this?

**Comment by thornpig** [comment]
I had the same problem. Then I figured out that I was not using this library correctly by initializing the instance of LIALinkedInHttpClient with
 [LIALinkedInHttpClient clientForApplication:application presentingViewController:nil];

Replacing the above "nil" to "self" solved the problem.

Thank you Jeyben for this great library!
