### ISSUE TITLE
permissions issue

### ISSUE THREAD

**Issue by PetrosDavtyan** [jeyben/IOSLinkedInAPI#53]
Hi everybody... 
When I add new permissions in
 [LIALinkedInApplicationapplicationWithRedirectURL:   clientId:   clientSecret:  state:  grantedAccess:@"Permssion1", @"Permssion2", etc];
method I don't receive expected result.
I always receive
result like this {
   firstName = fName;
   headline = "iOS developer";
   id = FI09uYt2w2;
   lastName = lName;
   siteStandardProfileRequest =     {
       url = "https://www.linkedin.com/profile/view?id=32442245&authType=name&authToken=Vze-&trk=api*a4353471*s4416641*";
   };
}

**Comment by pedro380085** [comment]
@PetrosDavtyan You must call the additional parameters you want to receive from their Profile API. Authorization ≠ Fields.

**Comment by PetrosDavtyan** [comment]
@pedro380085 can you show me an example please? I have already done that but don't receive what I want

**Comment by pedro380085** [comment]
```
- (void)requestMeWithToken:(NSString *)accessToken {
  [self.client GET:[NSString stringWithFormat:@"https://api.linkedin.com/v1/people/~?oauth2_access_token=%@&format=json", accessToken] parameters:nil success:^(AFHTTPRequestOperation *operation, NSDictionary *result) {
    NSLog(@"current user %@", result);
  }        failure:^(AFHTTPRequestOperation *operation, NSError *error) {
    NSLog(@"failed to fetch current user %@", error);
  }];
}
```

As stated on README.

**Comment by PetrosDavtyan** [comment]
I am doing it by this way, but don't receive anything  exept this 
{
firstName = fName;
headline = "iOS developer";
id = FI09uYt2w2;
lastName = lName;
siteStandardProfileRequest = {
url = "https://www.linkedin.com/profile/view?id=32442245&authType=name&authToken=Vze-&trk=api*a4353471*s4416641*";
};
}

**Comment by pedro380085** [comment]
@PetrosDavtyan, just ask for more fields on your URL: `https://api.linkedin.com/v1/people/~:(id,num-connections,picture-url)?format=json`
