### ISSUE TITLE
[!] Unable to find a specification for `ioslinkedinapi`

### ISSUE THREAD

**Issue by datomnurdin** [jeyben/IOSLinkedInAPI#57]
As per subject, I got this error when I trying to install IOSLinkedinAPI via cocoapod.

```
[!] Unable to find a specification for `ioslinkedinapi`
```

Please advice. Thank you.

**Comment by jeyben** [comment]
The specification is hosted at github under specs as all other public accessible open source projects.

Which version are you requesting?

**Comment by jeyben** [comment]
I will close this issue
