### ISSUE TITLE
Login Error

### ISSUE THREAD

**Issue by Zuzic** [jeyben/IOSLinkedInAPI#58]
Hi All,

I have some problems, I have created app in linkedIn site and have the redirect url, but I can't see web page for login, I have got error: Authorization failed Error Domain=LIALinkedInERROR Code=1 "The operation couldn’t be completed. (LIALinkedInERROR error 1.)"
Until May 12, the application works fine, after I started getting this error. Can YOU help me? Please

**Comment by realtybaron** [comment]
LinkedIn restricted access to their API significantly on May 12th:
https://developer.linkedin.com/blog/posts/2015/developer-program-changes

On Tue, May 26, 2015 at 2:44 PM, Yury Zenko <notifications@github.com>
wrote:

> Hi All,
>
> I have some problems, I have created app in linkedIn site and have the
> redirect url, but I can't see web page for login, I have got error:
> Authorization failed Error Domain=LIALinkedInERROR Code=1 "The operation
> couldn’t be completed. (LIALinkedInERROR error 1.)"
> Until May 12, the application works fine, after I started getting this
> error. Can YOU help me? Please
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jeyben/IOSLinkedInAPI/issues/58>.
>



-- 
Marc Dugger
mdugger@gmail.com

**Comment by jeyben** [comment]
Unfortunately as realty baron stated. LinkedIn has applied several restrictions to their API usages as long as you aren't a partner.

**Comment by ispha** [comment]
I had the same problem before checking latest updates of Linked In , but now it worked by removing r_publicprofile and r_publicnetwork then updating my App on linked in developer portal .

Then , replaced these two in granted permissions  in code by this one :r_basicprofile ,,and for sure updated both client id and secret one there !
