### ISSUE TITLE
LIALinkedInERROR error 1.

### ISSUE THREAD

**Issue by mixo44** [jeyben/IOSLinkedInAPI#59]
Hello. Please help me solve this error.

**`Authorization failed Error Domain=LIALinkedInERROR Code=1 "The operation couldn’t be completed. (LIALinkedInERROR error 1.)`**

I get this error when I ask **`r_fullprofile`** access.

### What should I do ? Is any way to fix this issue ?

**Comment by fel-cesar** [comment]
The API of LinkedIn Has changed. I solved this error by setting like this:

![screen shot 2015-06-17 at 17 47 15](https://cloud.githubusercontent.com/assets/4176646/8218396/fc3cce98-1518-11e5-9ecf-4bd6b206c712.png)

And in my APPs developer console i set the permissions like this:
![screen shot 2015-06-17 at 17 46 31](https://cloud.githubusercontent.com/assets/4176646/8218397/fc3fe07e-1518-11e5-9816-b7edba111ac4.png)

Both needs to be exactly the same, otherwise you`ll get ERROR 1.

**Comment by felix-dumit** [comment]
I'm still getting this issue, here is how my code is:

```objc
    LIALinkedInApplication *application = [LIALinkedInApplication applicationWithRedirectURL:@"https://website.com"
                                                                                    clientId:@"????"
                                                                                clientSecret:@"????"
                                                                                       state:@"????"
                                                                               grantedAccess:@[@"r_basicprofile", @"r_network", @"r_emailaddress"]];
```

Here's what my permissions look like:
![screen shot 2015-06-19 at 11 32 22 pm](https://cloud.githubusercontent.com/assets/1863251/8265697/fc06cc84-16db-11e5-9bfd-140a20648977.png)


Also where do I get the state string from? A previous developer implemented it I don't know where that came from.

**Comment by fel-cesar** [comment]
Hi @felix-dumit ,
the STATE string its an arbitrary string that is used to identify your request on linkedin server side  (if i am not wrong). It can be any string as long as it is UNIQUE, to avoid simultaneous conflicts on the server side. I recommend to use a hash or a code thats hard to repeat. like 
@"shdaksdl2gl3kj132l31v2lh3f12"

or 

@"HJ1K2JH31JJ12HF3KJ1K"

for the other problem i dont know whats might be the problem , BUT, try to use an array in the SAME order thats on the "Default applications Permissions", OR replicate my code (with full permissions), and see if it works.

**Comment by felix-dumit** [comment]
Ok thanks, I ended up removing the `r_network` permission and it worked. It was enabled but it was complaining that it wasn't   :confused:

**Comment by romaopedro** [comment]
Thank you very much. Removing r_network helped
