### ISSUE TITLE
redirect url issue

### ISSUE THREAD

**Issue by ahsolanki** [jeyben/IOSLinkedInAPI#60]
Getting this issue everytime
Authorization failed Error Domain=LIALinkedInERROR Code=1 "The operation couldn’t be completed. (LIALinkedInERROR error 1.)

**Comment by jeyben** [comment]
LinkedIn changed the conditions in the usage of their API´s recently (see the top of the readme.md). 
You could also see this issue for a suggested solution:
https://github.com/jeyben/IOSLinkedInAPI/issues/59
