### ISSUE TITLE
LIALinkedInERROR Code=2... state values do not match for some unknown reason

### ISSUE THREAD

**Issue by vanNiewoehner** [jeyben/IOSLinkedInAPI#73]
Hi,
I used the IOSLinkedInAPI for a couple of months without any issues, but since today, our users are no longer able to login. For some reason, the state values do not match and the one I get back from  LinkedIn is always followed by a "#!". So for example, I send the state "abcde" and get back "abcde#!".

Is anyone else experiencing this issue or knows if LinkedIn made some changes to in their API?

Thank you in advance!!

**Comment by jeyben** [comment]
If you use the master branch as your dependency, this has been fixed: https://github.com/jeyben/IOSLinkedInAPI/pull/71

**Comment by vanNiewoehner** [comment]
Thanks!

**Comment by adamcjohnson** [comment]
@jeyben Can we get this fix included in the Cocoapod?

**Comment by eyalzohar** [comment]
Hey,
Can we get this fix included in the Cocoapod?

Thank you
